# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptive_information', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_information', models.CharField(blank=True, help_text=b'Box number or ID number', max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, help_text=b'Street name and number', max_length=255)),
                ('city', models.CharField(help_text=b'City name', max_length=255)),
                ('state', models.CharField(blank=True, help_text=b'State name', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(help_text=b'Country name', max_length=255)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
            ],
        ),
    ]
