# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterField(
            model_name='repository',
            name='descriptive_information',
            field=models.CharField(blank=True, help_text=b'Additional collection data or Foundation name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(blank=True, help_text=b'Collection name or Descriptive name', max_length=255, null=True),
        ),
    ]
